package Daby::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Daby::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:daby',
        user => 'daby',
        password => 'daby',
    }
);

=head1 NAME

Daby::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Daby>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Daby::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.63

=head1 AUTHOR

Chitale, Ajay Shrikant

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
